language: ruby
rvm:
- 2.7

install: gem install jekyll html-proofer github-pages
script: "bundle exec jekyll build && bundle exec htmlproofer ./_site --disable-external"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
