# Site settings
title: Rittme.com
email: bernardo@rittme.com
description: > # this means to ignore newlines until "baseurl:"
  Hello there, this is my personal website, where I talk about my work
  and try to write about some interesting stuff. Please, take a look and
  send me a line if you like it.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rittme.com"
twitter_username: rittmeyer
github_username:  rittme
portrait: /images/me.png

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true