# Site settings
title: Rittme.com
email: bernardo@rittme.com
description: > # this means to ignore newlines until "baseurl:"
  Bernardo Rittmeyer personal blog. Here you can find some of my thoughts on software and life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.rittme.com"
twitter_username: rittmeyer
github_username:  rittme
linkedin_username: bernardorittmeyer

google_analytics: UA-12517401-1
exclude: [vendor]

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "mozilla-2014"
    values:
      sitemap: false
  -
    scope:
      path: "mozilla-2015"
    values:
      sitemap: false